#!/usr/bin/env python3
"""Weekly performance report -> reports/YYYY-Www.md (committed to repo).

Pulls: Dev.to article stats (key already in secrets), Bluesky profile stats
(free public API), data-engine coverage + spend. No new credentials needed.
"""
import json
import os
from datetime import date
from pathlib import Path

ROOT = Path(__file__).parent.parent
OUT = ROOT / "reports" / f"{date.today():%Y-W%V}.md"


def devto_stats():
    key = os.environ.get("DEVTO_API_KEY")
    if not key:
        return None
    import requests
    r = requests.get("https://dev.to/api/articles/me/published?per_page=100",
                     headers={"api-key": key}, timeout=30)
    if r.status_code != 200:
        return None
    arts = r.json()
    return {
        "articles": len(arts),
        "views": sum(a.get("page_views_count", 0) for a in arts),
        "reactions": sum(a.get("public_reactions_count", 0) for a in arts),
        "comments": sum(a.get("comments_count", 0) for a in arts),
    }


def bsky_stats():
    handle = os.environ.get("BSKY_HANDLE")
    pw = os.environ.get("BSKY_APP_PASSWORD")
    if not all([handle, pw]):
        return None
    import requests
    s = requests.post("https://bsky.social/xrpc/com.atproto.server.createSession",
                      json={"identifier": handle, "password": pw}, timeout=30)
    if s.status_code != 200:
        return None
    tok = s.json()["accessJwt"]
    r = requests.get("https://bsky.social/xrpc/app.bsky.actor.getProfile",
                     headers={"Authorization": f"Bearer {tok}"},
                     params={"actor": handle}, timeout=30)
    if r.status_code != 200:
        return None
    d = r.json()
    return {"followers": d.get("followersCount", 0), "posts": d.get("postsCount", 0)}


def engine_stats():
    runs_dir = ROOT / "data" / "runs"
    total_runs = len(list(runs_dir.glob("*.json"))) if runs_dir.exists() else 0
    total_prompts = 0
    if runs_dir.exists():
        for f in runs_dir.glob("*.json"):
            total_prompts += len(json.loads(f.read_text()).get("results", []))
    spend = {}
    spend_f = ROOT / "data" / "spend.json"
    if spend_f.exists():
        spend = json.loads(spend_f.read_text())
    pairs = 0
    index_f = ROOT / "data" / "index.json"
    if index_f.exists():
        pairs = len(json.loads(index_f.read_text()).get("pairs", []))
    return {"run_days": total_runs, "prompts_tested": total_prompts,
            "month_spend": spend.get("estimated_usd", 0), "stat_pages": pairs}


def main():
    e = engine_stats()
    d = devto_stats()
    b = bsky_stats()
    x_posts = 0
    xf = ROOT / "data" / "x_posts.json"
    if xf.exists():
        x_posts = json.loads(xf.read_text()).get("posts", 0)

    lines = [
        f"# Weekly report — {date.today():%d %B %Y}",
        "",
        "## Data engine",
        f"- Test days so far: {e['run_days']}",
        f"- Prompts tested: {e['prompts_tested']}",
        f"- Month spend: ${e['month_spend']:.2f} / $5.00 cap",
        f"- Stat pages live: {e['stat_pages']}",
        "",
        "## Syndication (Dev.to)",
    ]
    if d:
        lines += [f"- Articles: {d['articles']}", f"- Total views: {d['views']}",
                  f"- Reactions: {d['reactions']}", f"- Comments: {d['comments']}"]
    else:
        lines.append("- (key not set)")
    lines += ["", "## Social"]
    lines.append(f"- X posts this month: {x_posts} / 31 cap")
    if b:
        lines += [f"- Bluesky followers: {b['followers']}", f"- Bluesky posts: {b['posts']}"]
    lines += ["", "_Auto-generated by engine/report.py_"]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"Report written: {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
